(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)



(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SCA] ] = Range[ 6 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MM,
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "tt" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "phi" },

S[3] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "phi2" },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqL,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "suL" },

S[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqL,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "scL" },

S[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqL,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "stL" },

S[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqR,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "suR" },

S[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqR,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "scR" },

S[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqR,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "stR" },

S[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqL,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "sdL" },

S[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqL,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "ssL" },

S[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqL,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "sbL" },

S[13] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqR,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "sdR" },

S[14] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqR,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "ssR" },

S[15] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MsqR,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "sbR" },

S[16] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber, -Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslL,
    Indices -> {},
    PropagatorLabel -> "selL" },

S[17] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber, -Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslL,
    Indices -> {},
    PropagatorLabel -> "smuL" },

S[18] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber, -Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslL,
    Indices -> {},
    PropagatorLabel -> "staL" },

S[19] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber, -Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslR,
    Indices -> {},
    PropagatorLabel -> "selR" },

S[20] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber, -Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslR,
    Indices -> {},
    PropagatorLabel -> "smuR" },

S[21] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber, -Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslR,
    Indices -> {},
    PropagatorLabel -> "staR" },

S[22] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslL,
    Indices -> {},
    PropagatorLabel -> "sn1L" },

S[23] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslL,
    Indices -> {},
    PropagatorLabel -> "sn2L" },

S[24] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslL,
    Indices -> {},
    PropagatorLabel -> "sn3L" },

S[25] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslR,
    Indices -> {},
    PropagatorLabel -> "sn1R" },

S[26] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslR,
    Indices -> {},
    PropagatorLabel -> "sn2R" },

S[27] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MslR,
    Indices -> {},
    PropagatorLabel -> "sn3R" }
}


(*        Definitions       *)

GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

Me[ ___ ] := Me;
MM[ ___ ] := MM;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MH[ ___ ] := MH;
MsqL[ ___ ] := MsqL;
MsqR[ ___ ] := MsqR;
MslL[ ___ ] := MslL;
MslR[ ___ ] := MslR;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ S[4, {__}] ] := TheLabel[S[4]];
TheLabel[ S[5, {__}] ] := TheLabel[S[5]];
TheLabel[ S[6, {__}] ] := TheLabel[S[6]];
TheLabel[ S[7, {__}] ] := TheLabel[S[7]];
TheLabel[ S[8, {__}] ] := TheLabel[S[8]];
TheLabel[ S[9, {__}] ] := TheLabel[S[9]];
TheLabel[ S[10, {__}] ] := TheLabel[S[10]];
TheLabel[ S[11, {__}] ] := TheLabel[S[11]];
TheLabel[ S[12, {__}] ] := TheLabel[S[12]];
TheLabel[ S[13, {__}] ] := TheLabel[S[13]];
TheLabel[ S[14, {__}] ] := TheLabel[S[14]];
TheLabel[ S[15, {__}] ] := TheLabel[S[15]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3, 0, 0}, {I*gc3, 0, 0}, {I*gc3, 0, 0}, {(-I)*gc3, 0, 0}, {(-I)*gc3, 0, 0}, {I*gc3, 0, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4, 0, 0}, {(-I)*gc4, 0, 0}, {(2*I)*gc4, 0, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5, 0, 0}, {I*gc5, 0, 0}, {I*gc5, 0, 0}, {(-I)*gc5, 0, 0}, {(-I)*gc5, 0, 0}, {I*gc5, 0, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6, 0, 0}, {(-I)*gc6, 0, 0}, {(2*I)*gc6, 0, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7, 0, 0}, {I*gc7, 0, 0}, {I*gc7, 0, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8, 0, 0}, {(-I)*gc8, 0, 0}, {(2*I)*gc8, 0, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0, 0}},

C[ S[1] , S[1] , S[2] , S[2] ] == {{(-2*I)*lam, 0, 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0, 0}},

C[ S[1] , S[1] , S[3] , -S[3] ] == {{(-2*I)*lam, 0, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*v, 0, 0}},

C[ S[1] , S[2] , S[2] ] == {{(-2*I)*lam*v, 0, 0}},

C[ S[1] , S[3] , -S[3] ] == {{(-2*I)*lam*v, 0, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc19, 0, 0}, {I*gc19, 0, 0}},

C[ S[1] , -S[3] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*v)/(2*sw), 0, 0}},

C[ S[1] , -S[3] , V[3] ] == {{-gc23, 0, 0}, {gc23, 0, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc24, 0, 0}, {I*gc24, 0, 0}},

C[ S[1] , S[3] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0, 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*v)/(2*sw), 0, 0}},

C[ S[1] , S[3] , -V[3] ] == {{-gc28, 0, 0}, {gc28, 0, 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc29, 0, 0}, {I*gc29, 0, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*v)/sw^2, 0, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0, 0}},

C[ S[1] , S[2] , V[2] ] == {{-gc35, 0, 0}, {gc35, 0, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc36, 0, 0}, {I*gc36, 0, 0}},

C[ S[1] , -S[3] , V[3] , V[2] ] == {{EL^2/(2*cw), 0, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0, 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*v)/(2*cw), 0, 0}},

C[ S[1] , S[3] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*v)/(2*cw), 0, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0, 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0, 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*v)/(cw^2*sw^2), 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[4, {e3x2}] ] == {{I*gc47*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc47*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[4, {e3x2}] ] == {{I*gc48*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc48*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[4, {e1x2}] ] == {{I*gc49*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc49*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[4, {e3x2}] ] == {{I*gc50*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc50*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[4, {e1x2}] ] == {{I*gc51*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc51*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[4, {e1x2}] ] == {{I*gc52*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc52*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc53*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc54*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc55*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc56*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc57*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc58*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc59*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc60*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc61*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[2] ] == {{I*gc62L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc62R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[2] ] == {{I*gc63L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc63R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[11, {e2x2}] , F[11, {e1x2}] , V[2] ] == {{I*gc64L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc64R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc65L, 0, 0}, {I*gc65R, 0, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc66L, 0, 0}, {I*gc66R, 0, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc67L, 0, 0}, {I*gc67R, 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[2] ] == {{I*gc68L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc68R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e2x2}] , F[9, {e1x2}] , V[2] ] == {{I*gc69L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc69R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[7, {e2x2}] , F[7, {e1x2}] , V[2] ] == {{I*gc70L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc70R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc71, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc72, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc73, 0, 0}, {0, 0, 0}},

C[ -F[12, {e3x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc74*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc74*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[10, {e3x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc75*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc75*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc76*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc76*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc77, 0, 0}, {I*gc77, 0, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc78, 0, 0}, {I*gc78, 0, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc79, 0, 0}, {I*gc79, 0, 0}},

C[ -F[8, {e3x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc80*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc80*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc81*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc81*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc82*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc82*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc83, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc84, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc85, 0, 0}, {0, 0, 0}},

C[ -F[8, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc86*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc87*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc88*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc89*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc90*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc91*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc92*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc93*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc94*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc95, 0, 0}, {0, 0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc96, 0, 0}, {0, 0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc97, 0, 0}, {0, 0, 0}},

C[ -F[10, {e2x2}] , F[8, {e1x2}] , -S[3] ] == {{gc98L*IndexDelta[e1x2, e2x2], 0, 0}, {gc98R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e1x2}] , F[9, {e3x2}] , -S[3] ] == {{gc99L*IndexDelta[e1x2, e3x2], 0, 0}, {gc99R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[10, {e1x2}] , F[7, {e3x2}] , -S[3] ] == {{gc100L*IndexDelta[e1x2, e3x2], 0, 0}, {gc100R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , S[1] ] == {{I*gc101*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc101*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , S[2] ] == {{gc102L*IndexDelta[e1x2, e2x2], 0, 0}, {gc102R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc103L*IndexDelta[e1x2, e2x2], 0, 0}, {gc103R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[10, {e1x2}] , S[3] ] == {{gc104L*IndexDelta[e1x2, e3x2], 0, 0}, {gc104R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[10, {e1x2}] , S[3] ] == {{gc105L*IndexDelta[e1x2, e3x2], 0, 0}, {gc105R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[8, {e1x2}] , -S[3] ] == {{gc106L*IndexDelta[e1x2, e3x2], 0, 0}, {gc106R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[11, {e2x2}] , F[9, {e3x2}] , -S[3] ] == {{gc107L*IndexDelta[e2x2, e3x2], 0, 0}, {gc107R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e2x2}] , F[7, {e3x2}] , -S[3] ] == {{gc108L*IndexDelta[e2x2, e3x2], 0, 0}, {gc108R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc109*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc109*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , S[2] ] == {{gc110L*IndexDelta[e2x2, e3x2], 0, 0}, {gc110R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[8, {e1x2}] , F[11, {e3x2}] , S[3] ] == {{gc111L*IndexDelta[e1x2, e3x2], 0, 0}, {gc111R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[9, {e3x2}] , F[11, {e2x2}] , S[3] ] == {{gc112L*IndexDelta[e2x2, e3x2], 0, 0}, {gc112R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[11, {e2x2}] , S[3] ] == {{gc113L*IndexDelta[e2x2, e3x2], 0, 0}, {gc113R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc114L*IndexDelta[e1x2, e2x2], 0, 0}, {gc114R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[12, {e1x2}] , F[9, {e3x2}] , -S[3] ] == {{gc115L*IndexDelta[e1x2, e3x2], 0, 0}, {gc115R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[12, {e1x2}] , F[7, {e3x2}] , -S[3] ] == {{gc116L*IndexDelta[e1x2, e3x2], 0, 0}, {gc116R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , S[1] ] == {{I*gc117*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc117*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , S[2] ] == {{gc118L*IndexDelta[e1x2, e2x2], 0, 0}, {gc118R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[8, {e2x2}] , F[12, {e1x2}] , S[3] ] == {{gc119L*IndexDelta[e1x2, e2x2], 0, 0}, {gc119R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[12, {e1x2}] , S[3] ] == {{gc120L*IndexDelta[e1x2, e3x2], 0, 0}, {gc120R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[12, {e1x2}] , S[3] ] == {{gc121L*IndexDelta[e1x2, e3x2], 0, 0}, {gc121R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc122, 0, 0}, {I*gc122, 0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc123L, 0, 0}, {gc123R, 0, 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc124, 0, 0}, {0, 0, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0, 0}, {gc125R, 0, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc126, 0, 0}, {I*gc126, 0, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc127L, 0, 0}, {gc127R, 0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc128, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0, 0}, {gc129R, 0, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc130, 0, 0}, {I*gc130, 0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc131L, 0, 0}, {gc131R, 0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc132, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0, 0}, {gc133R, 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc134*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc134*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , S[2] ] == {{gc135L*IndexDelta[e2x2, e3x2], 0, 0}, {gc135R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , S[1] ] == {{I*gc136*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc136*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , S[2] ] == {{gc137L*IndexDelta[e1x2, e2x2], 0, 0}, {gc137R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc138*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc138*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , S[2] ] == {{gc139L*IndexDelta[e2x2, e3x2], 0, 0}, {gc139R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc140, 0, 0}, {I*gc140, 0, 0}, {0, 0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc141, 0, 0}, {I*gc141, 0, 0}, {0, 0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{EL*MW, 0, 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc143, 0, 0}, {I*gc143, 0, 0}, {0, 0, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/2)*EL*MW)/sw, 0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL*MW)/(2*sw), 0, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc146, 0, 0}, {I*gc146, 0, 0}, {0, 0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc147, 0, 0}, {I*gc147, 0, 0}, {0, 0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL*MW*(cw - sw)*(cw + sw))/(2*cw*sw), 0, 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc149, 0, 0}, {I*gc149, 0, 0}, {0, 0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL*MW), 0, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc151, 0, 0}, {I*gc151, 0, 0}, {0, 0, 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/2)*EL*MW)/sw, 0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL*MW)/(2*sw), 0, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc154, 0, 0}, {I*gc154, 0, 0}, {0, 0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc155, 0, 0}, {I*gc155, 0, 0}, {0, 0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL*MW*(cw - sw)*(cw + sw))/(2*cw*sw), 0, 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc157, 0, 0}, {I*gc157, 0, 0}, {0, 0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL*MZ)/(2*sw), 0, 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc159, 0, 0}, {I*gc159, 0, 0}, {0, 0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL*MZ)/(2*sw), 0, 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc161, 0, 0}, {I*gc161, 0, 0}, {0, 0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/2)*EL*MZ)/(cw*sw), 0, 0}},

C[ -U[5, {e2x1}] , U[5, {e3x1}] , V[4, {e1x2}] ] == {{gc163*SUNF[e1x2, e2x1, e3x1], 0, 0}, {gc163*SUNF[e1x2, e2x1, e3x1], 0, 0}, {0, 0, 0}},

C[ -F[10, {e2x2}] , F[12, {e1x2}] , S[24] ] == {{I*gc164*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[9, {e3x2}] , S[18] ] == {{I*gc165*IndexDelta[e1x2, e3x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[10, {e2x2}] , -S[24] ] == {{0, 0, 0}, {I*gc166R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[10, {e1x2}] , -S[18] ] == {{0, 0, 0}, {I*gc167R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[10, {e1x2}] , F[3] , S[12, {e2x1}] ] == {{I*gc168*IndexDelta[e1x2, e2x1], 0, 0}, {0, 0, 0}},

C[ -F[3] , F[10, {e1x2}] , -S[12, {e2x1}] ] == {{0, 0, 0}, {I*gc169R*IndexDelta[e1x2, e2x1], 0, 0}},

C[ -F[12, {e1x2}] , -F[3] , S[13, {e2x1}] ] == {{0, 0, 0}, {I*gc170R*IndexDelta[e1x2, e2x1], 0, 0}},

C[ -F[9, {e2x2}] , -F[6] , S[13, {e1x1}] ] == {{0, 0, 0}, {I*gc171R*IndexDelta[e1x1, e2x2], 0, 0}},

C[ F[12, {e1x2}] , F[3] , -S[13, {e2x1}] ] == {{I*gc172*IndexDelta[e1x2, e2x1], 0, 0}, {0, 0, 0}},

C[ F[9, {e2x2}] , F[6] , -S[13, {e1x1}] ] == {{I*gc173*IndexDelta[e1x1, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[6] , S[6, {e2x1}] ] == {{I*gc174*IndexDelta[e1x2, e2x1], 0, 0}, {0, 0, 0}},

C[ -F[6] , F[10, {e1x2}] , -S[6, {e2x1}] ] == {{0, 0, 0}, {I*gc175R*IndexDelta[e1x2, e2x1], 0, 0}},

C[ S[5, {e2x1}] , -S[5, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc176*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc176*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[8, {e2x1}] , -S[8, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc177*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc177*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[6, {e2x1}] , -S[6, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc178*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc178*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[9, {e2x1}] , -S[9, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc179*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc179*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[4, {e2x1}] , -S[4, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc180*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc180*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[7, {e2x1}] , -S[7, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc181*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc181*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[5, {e3x1}] , -S[5, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[8, {e3x1}] , -S[8, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[6, {e3x1}] , -S[6, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[9, {e3x1}] , -S[9, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[4, {e3x1}] , -S[4, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[7, {e3x1}] , -S[7, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[12, {e2x1}] , -S[12, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc188*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc188*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[15, {e2x1}] , -S[15, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc189*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc189*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[10, {e2x1}] , -S[10, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc190*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc190*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[13, {e2x1}] , -S[13, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc191*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc191*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[11, {e2x1}] , -S[11, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc192*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc192*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[14, {e2x1}] , -S[14, {e3x1}] , V[4, {e1x2}] ] == {{(-I)*gc193*SUNT[e1x2, e3x1, e2x1], 0, 0}, {I*gc193*SUNT[e1x2, e3x1, e2x1], 0, 0}},

C[ S[12, {e3x1}] , -S[12, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[15, {e3x1}] , -S[15, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[10, {e3x1}] , -S[10, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[13, {e3x1}] , -S[13, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[11, {e3x1}] , -S[11, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}},

C[ S[14, {e3x1}] , -S[14, {e4x1}] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{I*GS^2*(SUNT[e1x2, e2x2, e4x1, e3x1] + SUNT[e2x2, e1x2, e4x1, e3x1]), 0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> gw*sw,
     gc4 -> -(gw^2*sw^2),
     gc5 -> cw*gw,
     gc6 -> gw^2,
     gc7 -> cw*gw^2*sw,
     gc8 -> -(cw^2*gw^2),
     gc19 -> -EL,
     gc23 -> EL/(2*sw),
     gc24 -> EL/(2*sw),
     gc28 -> EL/(2*sw),
     gc29 -> -EL/(2*sw),
     gc35 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc36 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc47 -> GS,
     gc48 -> GS,
     gc49 -> GS,
     gc50 -> GS,
     gc51 -> GS,
     gc52 -> GS,
     gc53 -> (EL*Conjugate[CKM23])/(Sqrt[2]*sw),
     gc54 -> (EL*Conjugate[CKM33])/(Sqrt[2]*sw),
     gc55 -> (EL*Conjugate[CKM13])/(Sqrt[2]*sw),
     gc56 -> (EL*Conjugate[CKM21])/(Sqrt[2]*sw),
     gc57 -> (EL*Conjugate[CKM31])/(Sqrt[2]*sw),
     gc58 -> (EL*Conjugate[CKM11])/(Sqrt[2]*sw),
     gc59 -> (EL*Conjugate[CKM22])/(Sqrt[2]*sw),
     gc60 -> (EL*Conjugate[CKM32])/(Sqrt[2]*sw),
     gc61 -> (EL*Conjugate[CKM12])/(Sqrt[2]*sw),
     gc62L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc62R -> (EL*sw)/(3*cw),
     gc63L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc63R -> (EL*sw)/(3*cw),
     gc64L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc64R -> (EL*sw)/(3*cw),
     gc65L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc65R -> (EL*sw)/cw,
     gc66L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc66R -> (EL*sw)/cw,
     gc67L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc67R -> (EL*sw)/cw,
     gc68L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc68R -> (-2*EL*sw)/(3*cw),
     gc69L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc69R -> (-2*EL*sw)/(3*cw),
     gc70L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc70R -> (-2*EL*sw)/(3*cw),
     gc71 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc72 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc73 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc74 -> -EL/3,
     gc75 -> -EL/3,
     gc76 -> -EL/3,
     gc77 -> -EL,
     gc78 -> -EL,
     gc79 -> -EL,
     gc80 -> (2*EL)/3,
     gc81 -> (2*EL)/3,
     gc82 -> (2*EL)/3,
     gc83 -> EL/(Sqrt[2]*sw),
     gc84 -> EL/(Sqrt[2]*sw),
     gc85 -> EL/(Sqrt[2]*sw),
     gc86 -> (CKM23*EL)/(Sqrt[2]*sw),
     gc87 -> (CKM21*EL)/(Sqrt[2]*sw),
     gc88 -> (CKM22*EL)/(Sqrt[2]*sw),
     gc89 -> (CKM33*EL)/(Sqrt[2]*sw),
     gc90 -> (CKM31*EL)/(Sqrt[2]*sw),
     gc91 -> (CKM32*EL)/(Sqrt[2]*sw),
     gc92 -> (CKM13*EL)/(Sqrt[2]*sw),
     gc93 -> (CKM11*EL)/(Sqrt[2]*sw),
     gc94 -> (CKM12*EL)/(Sqrt[2]*sw),
     gc95 -> EL/(Sqrt[2]*sw),
     gc96 -> EL/(Sqrt[2]*sw),
     gc97 -> EL/(Sqrt[2]*sw),
     gc98L -> ydo*Conjugate[CKM21],
     gc98R -> -(yc*Conjugate[CKM21]),
     gc99L -> ydo*Conjugate[CKM31],
     gc99R -> -(yt*Conjugate[CKM31]),
     gc100L -> ydo*Conjugate[CKM11],
     gc100R -> -(yup*Conjugate[CKM11]),
     gc101 -> -(ydo/Sqrt[2]),
     gc102L -> -(ydo/Sqrt[2]),
     gc102R -> ydo/Sqrt[2],
     gc103L -> CKM21*yc,
     gc103R -> -(CKM21*ydo),
     gc104L -> CKM31*yt,
     gc104R -> -(CKM31*ydo),
     gc105L -> CKM11*yup,
     gc105R -> -(CKM11*ydo),
     gc106L -> ys*Conjugate[CKM22],
     gc106R -> -(yc*Conjugate[CKM22]),
     gc107L -> ys*Conjugate[CKM32],
     gc107R -> -(yt*Conjugate[CKM32]),
     gc108L -> ys*Conjugate[CKM12],
     gc108R -> -(yup*Conjugate[CKM12]),
     gc109 -> -(ys/Sqrt[2]),
     gc110L -> -(ys/Sqrt[2]),
     gc110R -> ys/Sqrt[2],
     gc111L -> CKM22*yc,
     gc111R -> -(CKM22*ys),
     gc112L -> CKM32*yt,
     gc112R -> -(CKM32*ys),
     gc113L -> CKM12*yup,
     gc113R -> -(CKM12*ys),
     gc114L -> yb*Conjugate[CKM23],
     gc114R -> -(yc*Conjugate[CKM23]),
     gc115L -> yb*Conjugate[CKM33],
     gc115R -> -(yt*Conjugate[CKM33]),
     gc116L -> yb*Conjugate[CKM13],
     gc116R -> -(yup*Conjugate[CKM13]),
     gc117 -> -(yb/Sqrt[2]),
     gc118L -> -(yb/Sqrt[2]),
     gc118R -> yb/Sqrt[2],
     gc119L -> CKM23*yc,
     gc119R -> -(CKM23*yb),
     gc120L -> CKM33*yt,
     gc120R -> -(CKM33*yb),
     gc121L -> CKM13*yup,
     gc121R -> -(CKM13*yb),
     gc122 -> -(ye/Sqrt[2]),
     gc123L -> -(ye/Sqrt[2]),
     gc123R -> ye/Sqrt[2],
     gc124 -> ye,
     gc125L -> 1,
     gc125R -> -ye,
     gc126 -> -(ym/Sqrt[2]),
     gc127L -> -(ym/Sqrt[2]),
     gc127R -> ym/Sqrt[2],
     gc128 -> ym,
     gc129L -> 1,
     gc129R -> -ym,
     gc130 -> -(ytau/Sqrt[2]),
     gc131L -> -(ytau/Sqrt[2]),
     gc131R -> ytau/Sqrt[2],
     gc132 -> ytau,
     gc133L -> 1,
     gc133R -> -ytau,
     gc134 -> -(yup/Sqrt[2]),
     gc135L -> yup/Sqrt[2],
     gc135R -> -(yup/Sqrt[2]),
     gc136 -> -(yc/Sqrt[2]),
     gc137L -> yc/Sqrt[2],
     gc137R -> -(yc/Sqrt[2]),
     gc138 -> -(yt/Sqrt[2]),
     gc139L -> yt/Sqrt[2],
     gc139R -> -(yt/Sqrt[2]),
     gc140 -> EL,
     gc141 -> -EL,
     gc143 -> EL,
     gc146 -> -EL,
     gc147 -> -((cw*EL)/sw),
     gc149 -> (cw*EL)/sw,
     gc151 -> -EL,
     gc154 -> EL,
     gc155 -> (cw*EL)/sw,
     gc157 -> -((cw*EL)/sw),
     gc159 -> (cw*EL)/sw,
     gc161 -> -((cw*EL)/sw),
     gc163 -> GS,
     gc164 -> -LQD331,
     gc165 -> LQD331,
     gc166L -> 1,
     gc166R -> -LQD331,
     gc167L -> 1,
     gc167R -> LQD331,
     gc168 -> -LQD331,
     gc169L -> 1,
     gc169R -> -LQD331,
     gc170L -> 1,
     gc170R -> -LQD331,
     gc171L -> 1,
     gc171R -> LQD331,
     gc172 -> -LQD331,
     gc173 -> LQD331,
     gc174 -> LQD331,
     gc175L -> 1,
     gc175R -> LQD331,
     gc176 -> -GS,
     gc177 -> -GS,
     gc178 -> -GS,
     gc179 -> -GS,
     gc180 -> -GS,
     gc181 -> -GS,
     gc188 -> -GS,
     gc189 -> -GS,
     gc190 -> -GS,
     gc191 -> -GS,
     gc192 -> -GS,
     gc193 -> -GS};

