(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)



(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MM,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

V[5] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MxZ,
    Indices -> {},
    PropagatorLabel -> "xZ" },

V[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MxW,
    Indices -> {},
    PropagatorLabel -> "xW" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Me[ ___ ] := Me;
MM[ ___ ] := MM;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
MxZ[ ___ ] := MxZ;
MxW[ ___ ] := MxW;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2])}, {gc1*SUNF[e1x2, e2x2, e3x2]}, {gc1*SUNF[e1x2, e2x2, e3x2]}, {-(gc1*SUNF[e1x2, e2x2, e3x2])}, {-(gc1*SUNF[e1x2, e2x2, e3x2])}, {gc1*SUNF[e1x2, e2x2, e3x2]}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2])}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2])}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2])}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3}, {I*gc3}, {I*gc3}, {(-I)*gc3}, {(-I)*gc3}, {I*gc3}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4}, {(-I)*gc4}, {(2*I)*gc4}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5}, {I*gc5}, {I*gc5}, {(-I)*gc5}, {(-I)*gc5}, {I*gc5}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6}, {(-I)*gc6}, {(2*I)*gc6}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7}, {I*gc7}, {I*gc7}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8}, {(-I)*gc8}, {(2*I)*gc8}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc19}, {I*gc19}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw)}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*sw)}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc23}, {I*gc23}},

C[ -S[3] , S[1] , V[3] ] == {{-gc24}, {gc24}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw)}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw)}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc28}, {I*gc28}},

C[ S[3] , S[1] , -V[3] ] == {{-gc29}, {gc29}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw)}},

C[ S[2] , S[1] , V[2] ] == {{-gc35}, {gc35}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc36}, {I*gc36}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw)}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw)}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw)}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*cw)}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2)}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2)}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2)}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2)}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc47}, {0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc48}, {0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc49}, {0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc50}, {0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc51}, {0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc52}, {0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc53}, {I*gc53}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc54}, {I*gc54}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc55}, {I*gc55}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc56}, {0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc57}, {0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc58}, {0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc59L}, {I*gc59R}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc60L}, {I*gc60R}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc61L}, {I*gc61R}},

C[ -F[8, {e3x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc62*IndexDelta[e2x2, e3x2]}, {I*gc62*IndexDelta[e2x2, e3x2]}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc63*IndexDelta[e2x2, e3x2]}, {I*gc63*IndexDelta[e2x2, e3x2]}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc64*IndexDelta[e2x2, e3x2]}, {I*gc64*IndexDelta[e2x2, e3x2]}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[4, {e3x2}] ] == {{I*gc65*SUNT[e3x2, e2x2, e1x2]}, {I*gc65*SUNT[e3x2, e2x2, e1x2]}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[4, {e1x2}] ] == {{I*gc66*SUNT[e1x2, e3x2, e2x2]}, {I*gc66*SUNT[e1x2, e3x2, e2x2]}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[4, {e1x2}] ] == {{I*gc67*SUNT[e1x2, e3x2, e2x2]}, {I*gc67*SUNT[e1x2, e3x2, e2x2]}},

C[ -F[8, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc68*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc69*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc70*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[9, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc71*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[9, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc72*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[9, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc73*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[7, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc74*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[7, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc75*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[7, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc76*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[2] ] == {{I*gc77L*IndexDelta[e1x2, e2x2]}, {I*gc77R*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e2x2}] , F[9, {e1x2}] , V[2] ] == {{I*gc78L*IndexDelta[e1x2, e2x2]}, {I*gc78R*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e2x2}] , F[7, {e1x2}] , V[2] ] == {{I*gc79L*IndexDelta[e1x2, e2x2]}, {I*gc79R*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e3x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc80*IndexDelta[e2x2, e3x2]}, {I*gc80*IndexDelta[e2x2, e3x2]}},

C[ -F[10, {e3x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc81*IndexDelta[e2x2, e3x2]}, {I*gc81*IndexDelta[e2x2, e3x2]}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc82*IndexDelta[e2x2, e3x2]}, {I*gc82*IndexDelta[e2x2, e3x2]}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[4, {e3x2}] ] == {{I*gc83*SUNT[e3x2, e2x2, e1x2]}, {I*gc83*SUNT[e3x2, e2x2, e1x2]}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[4, {e3x2}] ] == {{I*gc84*SUNT[e3x2, e2x2, e1x2]}, {I*gc84*SUNT[e3x2, e2x2, e1x2]}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[4, {e1x2}] ] == {{I*gc85*SUNT[e1x2, e3x2, e2x2]}, {I*gc85*SUNT[e1x2, e3x2, e2x2]}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc86*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc87*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc88*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[10, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc89*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc90*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc91*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[11, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc92*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc93*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc94*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[2] ] == {{I*gc95L*IndexDelta[e1x2, e2x2]}, {I*gc95R*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[2] ] == {{I*gc96L*IndexDelta[e1x2, e2x2]}, {I*gc96R*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e2x2}] , F[11, {e1x2}] , V[2] ] == {{I*gc97L*IndexDelta[e1x2, e2x2]}, {I*gc97R*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc98L*IndexDelta[e1x2, e2x2]}, {gc98R*IndexDelta[e1x2, e2x2]}},

C[ -F[12, {e1x2}] , F[9, {e3x2}] , -S[3] ] == {{gc99L*IndexDelta[e1x2, e3x2]}, {gc99R*IndexDelta[e1x2, e3x2]}},

C[ -F[12, {e1x2}] , F[7, {e3x2}] , -S[3] ] == {{gc100L*IndexDelta[e1x2, e3x2]}, {gc100R*IndexDelta[e1x2, e3x2]}},

C[ -F[10, {e2x2}] , F[8, {e1x2}] , -S[3] ] == {{gc101L*IndexDelta[e1x2, e2x2]}, {gc101R*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[9, {e3x2}] , -S[3] ] == {{gc102L*IndexDelta[e1x2, e3x2]}, {gc102R*IndexDelta[e1x2, e3x2]}},

C[ -F[10, {e1x2}] , F[7, {e3x2}] , -S[3] ] == {{gc103L*IndexDelta[e1x2, e3x2]}, {gc103R*IndexDelta[e1x2, e3x2]}},

C[ -F[11, {e3x2}] , F[8, {e1x2}] , -S[3] ] == {{gc104L*IndexDelta[e1x2, e3x2]}, {gc104R*IndexDelta[e1x2, e3x2]}},

C[ -F[11, {e2x2}] , F[9, {e3x2}] , -S[3] ] == {{gc105L*IndexDelta[e2x2, e3x2]}, {gc105R*IndexDelta[e2x2, e3x2]}},

C[ -F[11, {e2x2}] , F[7, {e3x2}] , -S[3] ] == {{gc106L*IndexDelta[e2x2, e3x2]}, {gc106R*IndexDelta[e2x2, e3x2]}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , S[2] ] == {{gc107L*IndexDelta[e1x2, e2x2]}, {gc107R*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , S[2] ] == {{gc108L*IndexDelta[e1x2, e2x2]}, {gc108R*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , S[2] ] == {{gc109L*IndexDelta[e2x2, e3x2]}, {gc109R*IndexDelta[e2x2, e3x2]}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , S[1] ] == {{I*gc110*IndexDelta[e1x2, e2x2]}, {I*gc110*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , S[1] ] == {{I*gc111*IndexDelta[e1x2, e2x2]}, {I*gc111*IndexDelta[e1x2, e2x2]}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc112*IndexDelta[e2x2, e3x2]}, {I*gc112*IndexDelta[e2x2, e3x2]}},

C[ -F[4] , F[1] , -S[3] ] == {{gc113}, {0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc114}, {0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc115}, {0}},

C[ -F[4] , F[4] , S[2] ] == {{gc116L}, {gc116R}},

C[ -F[5] , F[5] , S[2] ] == {{gc117L}, {gc117R}},

C[ -F[6] , F[6] , S[2] ] == {{gc118L}, {gc118R}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc119}, {I*gc119}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc120}, {I*gc120}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc121}, {I*gc121}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , S[2] ] == {{gc122L*IndexDelta[e1x2, e2x2]}, {gc122R*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , S[2] ] == {{gc123L*IndexDelta[e2x2, e3x2]}, {gc123R*IndexDelta[e2x2, e3x2]}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , S[2] ] == {{gc124L*IndexDelta[e2x2, e3x2]}, {gc124R*IndexDelta[e2x2, e3x2]}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , S[1] ] == {{I*gc125*IndexDelta[e1x2, e2x2]}, {I*gc125*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc126*IndexDelta[e2x2, e3x2]}, {I*gc126*IndexDelta[e2x2, e3x2]}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc127*IndexDelta[e2x2, e3x2]}, {I*gc127*IndexDelta[e2x2, e3x2]}},

C[ -F[8, {e2x2}] , F[12, {e1x2}] , S[3] ] == {{gc128L*IndexDelta[e1x2, e2x2]}, {gc128R*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc129L*IndexDelta[e1x2, e2x2]}, {gc129R*IndexDelta[e1x2, e2x2]}},

C[ -F[8, {e1x2}] , F[11, {e3x2}] , S[3] ] == {{gc130L*IndexDelta[e1x2, e3x2]}, {gc130R*IndexDelta[e1x2, e3x2]}},

C[ -F[9, {e3x2}] , F[12, {e1x2}] , S[3] ] == {{gc131L*IndexDelta[e1x2, e3x2]}, {gc131R*IndexDelta[e1x2, e3x2]}},

C[ -F[9, {e3x2}] , F[10, {e1x2}] , S[3] ] == {{gc132L*IndexDelta[e1x2, e3x2]}, {gc132R*IndexDelta[e1x2, e3x2]}},

C[ -F[9, {e3x2}] , F[11, {e2x2}] , S[3] ] == {{gc133L*IndexDelta[e2x2, e3x2]}, {gc133R*IndexDelta[e2x2, e3x2]}},

C[ -F[7, {e3x2}] , F[12, {e1x2}] , S[3] ] == {{gc134L*IndexDelta[e1x2, e3x2]}, {gc134R*IndexDelta[e1x2, e3x2]}},

C[ -F[7, {e3x2}] , F[10, {e1x2}] , S[3] ] == {{gc135L*IndexDelta[e1x2, e3x2]}, {gc135R*IndexDelta[e1x2, e3x2]}},

C[ -F[7, {e3x2}] , F[11, {e2x2}] , S[3] ] == {{gc136L*IndexDelta[e2x2, e3x2]}, {gc136R*IndexDelta[e2x2, e3x2]}},

C[ -F[1] , F[4] , S[3] ] == {{0}, {gc137R}},

C[ -F[2] , F[5] , S[3] ] == {{0}, {gc138R}},

C[ -F[3] , F[6] , S[3] ] == {{0}, {gc139R}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc140}, {I*gc140}, {0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc141}, {I*gc141}, {0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw)}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc143}, {I*gc143}, {0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL^2*vev)/(4*sw^2)}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/4)*EL^2*vev)/sw^2}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc146}, {I*gc146}, {0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc147}, {I*gc147}, {0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2)}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc149}, {I*gc149}, {0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL^2*vev)/(2*sw)}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc151}, {I*gc151}, {0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2)}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/4)*EL^2*vev)/sw^2}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc154}, {I*gc154}, {0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc155}, {I*gc155}, {0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2)}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc157}, {I*gc157}, {0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2)}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc159}, {I*gc159}, {0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2)}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc161}, {I*gc161}, {0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2)}},

C[ -U[5, {e2x1}] , U[5, {e3x1}] , V[4, {e1x2}] ] == {{gc163*SUNF[e1x2, e2x1, e3x1]}, {gc163*SUNF[e1x2, e2x1, e3x1]}, {0}},

C[ -F[9, {e2x2}] , F[10, {e1x2}] , V[6] ] == {{I*gc164L*IndexDelta[e1x2, e2x2]}, {I*gc164R*IndexDelta[e1x2, e2x2]}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[6] ] == {{I*gc165L*IndexDelta[e1x2, e2x2]}, {I*gc165R*IndexDelta[e1x2, e2x2]}},

C[ -F[7, {e2x2}] , F[9, {e1x2}] , V[5] ] == {{0}, {I*gc166R*IndexDelta[e1x2, e2x2]}},

C[ -F[9, {e1x2}] , F[7, {e2x2}] , V[5] ] == {{0}, {I*gc167R*IndexDelta[e1x2, e2x2]}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> EL,
     gc4 -> -EL^2,
     gc5 -> (cw*EL)/sw,
     gc6 -> EL^2/sw^2,
     gc7 -> (cw*EL^2)/sw,
     gc8 -> -((cw^2*EL^2)/sw^2),
     gc19 -> -EL,
     gc23 -> EL/(2*sw),
     gc24 -> -EL/(2*sw),
     gc28 -> -EL/(2*sw),
     gc29 -> -EL/(2*sw),
     gc35 -> -(EL*(cw^2 + sw^2))/(2*cw*sw),
     gc36 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc47 -> EL/(Sqrt[2]*sw),
     gc48 -> EL/(Sqrt[2]*sw),
     gc49 -> EL/(Sqrt[2]*sw),
     gc50 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc51 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc52 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc53 -> -EL,
     gc54 -> -EL,
     gc55 -> -EL,
     gc56 -> EL/(Sqrt[2]*sw),
     gc57 -> EL/(Sqrt[2]*sw),
     gc58 -> EL/(Sqrt[2]*sw),
     gc59L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc59R -> (EL*sw)/cw,
     gc60L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc60R -> (EL*sw)/cw,
     gc61L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc61R -> (EL*sw)/cw,
     gc62 -> (2*EL)/3,
     gc63 -> (2*EL)/3,
     gc64 -> (2*EL)/3,
     gc65 -> GS,
     gc66 -> GS,
     gc67 -> GS,
     gc68 -> (CKM23*EL)/(Sqrt[2]*sw),
     gc69 -> (CKM21*EL)/(Sqrt[2]*sw),
     gc70 -> (CKM22*EL)/(Sqrt[2]*sw),
     gc71 -> (CKM33*EL)/(Sqrt[2]*sw),
     gc72 -> (CKM31*EL)/(Sqrt[2]*sw),
     gc73 -> (CKM32*EL)/(Sqrt[2]*sw),
     gc74 -> (CKM13*EL)/(Sqrt[2]*sw),
     gc75 -> (CKM11*EL)/(Sqrt[2]*sw),
     gc76 -> (CKM12*EL)/(Sqrt[2]*sw),
     gc77L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc77R -> (-2*EL*sw)/(3*cw),
     gc78L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc78R -> (-2*EL*sw)/(3*cw),
     gc79L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc79R -> (-2*EL*sw)/(3*cw),
     gc80 -> -EL/3,
     gc81 -> -EL/3,
     gc82 -> -EL/3,
     gc83 -> GS,
     gc84 -> GS,
     gc85 -> GS,
     gc86 -> (EL*Conjugate[CKM23])/(Sqrt[2]*sw),
     gc87 -> (EL*Conjugate[CKM33])/(Sqrt[2]*sw),
     gc88 -> (EL*Conjugate[CKM13])/(Sqrt[2]*sw),
     gc89 -> (EL*Conjugate[CKM21])/(Sqrt[2]*sw),
     gc90 -> (EL*Conjugate[CKM31])/(Sqrt[2]*sw),
     gc91 -> (EL*Conjugate[CKM11])/(Sqrt[2]*sw),
     gc92 -> (EL*Conjugate[CKM22])/(Sqrt[2]*sw),
     gc93 -> (EL*Conjugate[CKM32])/(Sqrt[2]*sw),
     gc94 -> (EL*Conjugate[CKM12])/(Sqrt[2]*sw),
     gc95L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc95R -> (EL*sw)/(3*cw),
     gc96L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc96R -> (EL*sw)/(3*cw),
     gc97L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc97R -> (EL*sw)/(3*cw),
     gc98L -> yb*Conjugate[CKM23],
     gc98R -> -(yc*Conjugate[CKM23]),
     gc99L -> yb*Conjugate[CKM33],
     gc99R -> -(yt*Conjugate[CKM33]),
     gc100L -> yb*Conjugate[CKM13],
     gc100R -> -(yup*Conjugate[CKM13]),
     gc101L -> ydo*Conjugate[CKM21],
     gc101R -> -(yc*Conjugate[CKM21]),
     gc102L -> ydo*Conjugate[CKM31],
     gc102R -> -(yt*Conjugate[CKM31]),
     gc103L -> ydo*Conjugate[CKM11],
     gc103R -> -(yup*Conjugate[CKM11]),
     gc104L -> ys*Conjugate[CKM22],
     gc104R -> -(yc*Conjugate[CKM22]),
     gc105L -> ys*Conjugate[CKM32],
     gc105R -> -(yt*Conjugate[CKM32]),
     gc106L -> ys*Conjugate[CKM12],
     gc106R -> -(yup*Conjugate[CKM12]),
     gc107L -> -(yb/Sqrt[2]),
     gc107R -> yb/Sqrt[2],
     gc108L -> -(ydo/Sqrt[2]),
     gc108R -> ydo/Sqrt[2],
     gc109L -> -(ys/Sqrt[2]),
     gc109R -> ys/Sqrt[2],
     gc110 -> -(yb/Sqrt[2]),
     gc111 -> -(ydo/Sqrt[2]),
     gc112 -> -(ys/Sqrt[2]),
     gc113 -> ye,
     gc114 -> ym,
     gc115 -> ytau,
     gc116L -> -(ye/Sqrt[2]),
     gc116R -> ye/Sqrt[2],
     gc117L -> -(ym/Sqrt[2]),
     gc117R -> ym/Sqrt[2],
     gc118L -> -(ytau/Sqrt[2]),
     gc118R -> ytau/Sqrt[2],
     gc119 -> -(ye/Sqrt[2]),
     gc120 -> -(ym/Sqrt[2]),
     gc121 -> -(ytau/Sqrt[2]),
     gc122L -> yc/Sqrt[2],
     gc122R -> -(yc/Sqrt[2]),
     gc123L -> yt/Sqrt[2],
     gc123R -> -(yt/Sqrt[2]),
     gc124L -> yup/Sqrt[2],
     gc124R -> -(yup/Sqrt[2]),
     gc125 -> -(yc/Sqrt[2]),
     gc126 -> -(yt/Sqrt[2]),
     gc127 -> -(yup/Sqrt[2]),
     gc128L -> CKM23*yc,
     gc128R -> -(CKM23*yb),
     gc129L -> CKM21*yc,
     gc129R -> -(CKM21*ydo),
     gc130L -> CKM22*yc,
     gc130R -> -(CKM22*ys),
     gc131L -> CKM33*yt,
     gc131R -> -(CKM33*yb),
     gc132L -> CKM31*yt,
     gc132R -> -(CKM31*ydo),
     gc133L -> CKM32*yt,
     gc133R -> -(CKM32*ys),
     gc134L -> CKM13*yup,
     gc134R -> -(CKM13*yb),
     gc135L -> CKM11*yup,
     gc135R -> -(CKM11*ydo),
     gc136L -> CKM12*yup,
     gc136R -> -(CKM12*ys),
     gc137L -> 1,
     gc137R -> -ye,
     gc138L -> 1,
     gc138R -> -ym,
     gc139L -> 1,
     gc139R -> -ytau,
     gc140 -> EL,
     gc141 -> -EL,
     gc143 -> EL,
     gc146 -> -EL,
     gc147 -> -((cw*EL)/sw),
     gc149 -> (cw*EL)/sw,
     gc151 -> -EL,
     gc154 -> EL,
     gc155 -> (cw*EL)/sw,
     gc157 -> -((cw*EL)/sw),
     gc159 -> (cw*EL)/sw,
     gc161 -> -((cw*EL)/sw),
     gc163 -> GS,
     gc164L -> -gWprimeL,
     gc164R -> -gWprimeR,
     gc165L -> -gWprimeL,
     gc165R -> -gWprimeR,
     gc166L -> 1,
     gc166R -> -gZprimeUT,
     gc167L -> 1,
     gc167R -> -gZprimeUT};

