(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)



(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MM,
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "tt" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "phi" },

S[3] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "phi2" }
}


(*        Definitions       *)

GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

Me[ ___ ] := Me;
MM[ ___ ] := MM;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MH[ ___ ] := MH;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3, 0, 0}, {I*gc3, 0, 0}, {I*gc3, 0, 0}, {(-I)*gc3, 0, 0}, {(-I)*gc3, 0, 0}, {I*gc3, 0, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4, 0, 0}, {(-I)*gc4, 0, 0}, {(2*I)*gc4, 0, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5, 0, 0}, {I*gc5, 0, 0}, {I*gc5, 0, 0}, {(-I)*gc5, 0, 0}, {(-I)*gc5, 0, 0}, {I*gc5, 0, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6, 0, 0}, {(-I)*gc6, 0, 0}, {(2*I)*gc6, 0, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7, 0, 0}, {I*gc7, 0, 0}, {I*gc7, 0, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8, 0, 0}, {(-I)*gc8, 0, 0}, {(2*I)*gc8, 0, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0, 0}},

C[ S[1] , S[1] , S[2] , S[2] ] == {{(-2*I)*lam, 0, 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0, 0}},

C[ S[1] , S[1] , S[3] , -S[3] ] == {{(-2*I)*lam, 0, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*v, 0, 0}},

C[ S[1] , S[2] , S[2] ] == {{(-2*I)*lam*v, 0, 0}},

C[ S[1] , S[3] , -S[3] ] == {{(-2*I)*lam*v, 0, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc19, 0, 0}, {I*gc19, 0, 0}},

C[ S[1] , -S[3] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0, 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*v)/(2*sw), 0, 0}},

C[ S[1] , -S[3] , V[3] ] == {{-gc23, 0, 0}, {gc23, 0, 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc24, 0, 0}, {I*gc24, 0, 0}},

C[ S[1] , S[3] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0, 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*v)/(2*sw), 0, 0}},

C[ S[1] , S[3] , -V[3] ] == {{-gc28, 0, 0}, {gc28, 0, 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc29, 0, 0}, {I*gc29, 0, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*v)/sw^2, 0, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0, 0}},

C[ S[1] , S[2] , V[2] ] == {{-gc35, 0, 0}, {gc35, 0, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc36, 0, 0}, {I*gc36, 0, 0}},

C[ S[1] , -S[3] , V[3] , V[2] ] == {{EL^2/(2*cw), 0, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0, 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*v)/(2*cw), 0, 0}},

C[ S[1] , S[3] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*v)/(2*cw), 0, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0, 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0, 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*v)/(cw^2*sw^2), 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[4, {e3x2}] ] == {{I*gc47*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc47*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[4, {e3x2}] ] == {{I*gc48*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc48*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[4, {e1x2}] ] == {{I*gc49*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc49*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[4, {e3x2}] ] == {{I*gc50*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc50*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[4, {e1x2}] ] == {{I*gc51*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc51*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[4, {e1x2}] ] == {{I*gc52*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc52*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[12, {e3x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc53*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc53*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[10, {e3x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc54*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc54*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc55*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc55*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc56, 0, 0}, {I*gc56, 0, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc57, 0, 0}, {I*gc57, 0, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc58, 0, 0}, {I*gc58, 0, 0}},

C[ -F[8, {e3x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc59*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc59*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc60*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc60*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc61*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc61*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc62, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc63, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc64, 0, 0}, {0, 0, 0}},

C[ -F[8, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc65*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc66*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc67*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc68*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc69*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc70*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc71*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc72*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc73*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc74, 0, 0}, {0, 0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc75, 0, 0}, {0, 0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc76, 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc77*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc78*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc79*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc80*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc81*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc82*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc83*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc84*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc85*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[2] ] == {{I*gc86L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc86R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[2] ] == {{I*gc87L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc87R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[11, {e2x2}] , F[11, {e1x2}] , V[2] ] == {{I*gc88L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc88R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc89L, 0, 0}, {I*gc89R, 0, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc90L, 0, 0}, {I*gc90R, 0, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc91L, 0, 0}, {I*gc91R, 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[2] ] == {{I*gc92L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc92R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e2x2}] , F[9, {e1x2}] , V[2] ] == {{I*gc93L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc93R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[7, {e2x2}] , F[7, {e1x2}] , V[2] ] == {{I*gc94L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc94R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc95, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc96, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc97, 0, 0}, {0, 0, 0}},

C[ -F[10, {e2x2}] , F[8, {e1x2}] , -S[3] ] == {{gc98L*IndexDelta[e1x2, e2x2], 0, 0}, {gc98R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e1x2}] , F[9, {e3x2}] , -S[3] ] == {{gc99L*IndexDelta[e1x2, e3x2], 0, 0}, {gc99R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[10, {e1x2}] , F[7, {e3x2}] , -S[3] ] == {{gc100L*IndexDelta[e1x2, e3x2], 0, 0}, {gc100R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , S[1] ] == {{I*gc101*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc101*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , S[2] ] == {{gc102L*IndexDelta[e1x2, e2x2], 0, 0}, {gc102R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{gc103L*IndexDelta[e1x2, e2x2], 0, 0}, {gc103R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[10, {e1x2}] , S[3] ] == {{gc104L*IndexDelta[e1x2, e3x2], 0, 0}, {gc104R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[10, {e1x2}] , S[3] ] == {{gc105L*IndexDelta[e1x2, e3x2], 0, 0}, {gc105R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[8, {e1x2}] , -S[3] ] == {{gc106L*IndexDelta[e1x2, e3x2], 0, 0}, {gc106R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[11, {e2x2}] , F[9, {e3x2}] , -S[3] ] == {{gc107L*IndexDelta[e2x2, e3x2], 0, 0}, {gc107R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e2x2}] , F[7, {e3x2}] , -S[3] ] == {{gc108L*IndexDelta[e2x2, e3x2], 0, 0}, {gc108R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc109*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc109*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , S[2] ] == {{gc110L*IndexDelta[e2x2, e3x2], 0, 0}, {gc110R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[8, {e1x2}] , F[11, {e3x2}] , S[3] ] == {{gc111L*IndexDelta[e1x2, e3x2], 0, 0}, {gc111R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[9, {e3x2}] , F[11, {e2x2}] , S[3] ] == {{gc112L*IndexDelta[e2x2, e3x2], 0, 0}, {gc112R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[11, {e2x2}] , S[3] ] == {{gc113L*IndexDelta[e2x2, e3x2], 0, 0}, {gc113R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{gc114L*IndexDelta[e1x2, e2x2], 0, 0}, {gc114R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[12, {e1x2}] , F[9, {e3x2}] , -S[3] ] == {{gc115L*IndexDelta[e1x2, e3x2], 0, 0}, {gc115R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[12, {e1x2}] , F[7, {e3x2}] , -S[3] ] == {{gc116L*IndexDelta[e1x2, e3x2], 0, 0}, {gc116R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , S[1] ] == {{I*gc117*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc117*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , S[2] ] == {{gc118L*IndexDelta[e1x2, e2x2], 0, 0}, {gc118R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[8, {e2x2}] , F[12, {e1x2}] , S[3] ] == {{gc119L*IndexDelta[e1x2, e2x2], 0, 0}, {gc119R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[12, {e1x2}] , S[3] ] == {{gc120L*IndexDelta[e1x2, e3x2], 0, 0}, {gc120R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[12, {e1x2}] , S[3] ] == {{gc121L*IndexDelta[e1x2, e3x2], 0, 0}, {gc121R*IndexDelta[e1x2, e3x2], 0, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc122, 0, 0}, {I*gc122, 0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc123L, 0, 0}, {gc123R, 0, 0}},

C[ -F[4] , F[1] , -S[3] ] == {{gc124, 0, 0}, {0, 0, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0, 0}, {gc125R, 0, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc126, 0, 0}, {I*gc126, 0, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc127L, 0, 0}, {gc127R, 0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{gc128, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0, 0}, {gc129R, 0, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc130, 0, 0}, {I*gc130, 0, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc131L, 0, 0}, {gc131R, 0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{gc132, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0, 0}, {gc133R, 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc134*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc134*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , S[2] ] == {{gc135L*IndexDelta[e2x2, e3x2], 0, 0}, {gc135R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , S[1] ] == {{I*gc136*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc136*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , S[2] ] == {{gc137L*IndexDelta[e1x2, e2x2], 0, 0}, {gc137R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc138*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc138*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , S[2] ] == {{gc139L*IndexDelta[e2x2, e3x2], 0, 0}, {gc139R*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc140, 0, 0}, {I*gc140, 0, 0}, {0, 0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc141, 0, 0}, {I*gc141, 0, 0}, {0, 0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{EL*MW, 0, 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc143, 0, 0}, {I*gc143, 0, 0}, {0, 0, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-I/2)*EL*MW)/sw, 0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-(EL*MW)/(2*sw), 0, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc146, 0, 0}, {I*gc146, 0, 0}, {0, 0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc147, 0, 0}, {I*gc147, 0, 0}, {0, 0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL*MW*(cw - sw)*(cw + sw))/(2*cw*sw), 0, 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc149, 0, 0}, {I*gc149, 0, 0}, {0, 0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-(EL*MW), 0, 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc151, 0, 0}, {I*gc151, 0, 0}, {0, 0, 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-I/2)*EL*MW)/sw, 0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL*MW)/(2*sw), 0, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc154, 0, 0}, {I*gc154, 0, 0}, {0, 0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc155, 0, 0}, {I*gc155, 0, 0}, {0, 0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-(EL*MW*(cw - sw)*(cw + sw))/(2*cw*sw), 0, 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc157, 0, 0}, {I*gc157, 0, 0}, {0, 0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL*MZ)/(2*sw), 0, 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc159, 0, 0}, {I*gc159, 0, 0}, {0, 0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-(EL*MZ)/(2*sw), 0, 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc161, 0, 0}, {I*gc161, 0, 0}, {0, 0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/2)*EL*MZ)/(cw*sw), 0, 0}},

C[ -U[5, {e2x1}] , U[5, {e3x1}] , V[4, {e1x2}] ] == {{gc163*SUNF[e1x2, e2x1, e3x1], 0, 0}, {gc163*SUNF[e1x2, e2x1, e3x1], 0, 0}, {0, 0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> gw*sw,
     gc4 -> -(gw^2*sw^2),
     gc5 -> cw*gw,
     gc6 -> gw^2,
     gc7 -> cw*gw^2*sw,
     gc8 -> -(cw^2*gw^2),
     gc19 -> -EL,
     gc23 -> EL/(2*sw),
     gc24 -> EL/(2*sw),
     gc28 -> EL/(2*sw),
     gc29 -> -EL/(2*sw),
     gc35 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc36 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc47 -> GS,
     gc48 -> GS,
     gc49 -> GS,
     gc50 -> GS,
     gc51 -> GS,
     gc52 -> GS,
     gc53 -> -EL/3,
     gc54 -> -EL/3,
     gc55 -> -EL/3,
     gc56 -> -EL,
     gc57 -> -EL,
     gc58 -> -EL,
     gc59 -> (2*EL)/3,
     gc60 -> (2*EL)/3,
     gc61 -> (2*EL)/3,
     gc62 -> EL/(Sqrt[2]*sw),
     gc63 -> EL/(Sqrt[2]*sw),
     gc64 -> EL/(Sqrt[2]*sw),
     gc65 -> (CKM23*EL)/(Sqrt[2]*sw),
     gc66 -> (CKM21*EL)/(Sqrt[2]*sw),
     gc67 -> (CKM22*EL)/(Sqrt[2]*sw),
     gc68 -> (CKM33*EL)/(Sqrt[2]*sw),
     gc69 -> (CKM31*EL)/(Sqrt[2]*sw),
     gc70 -> (CKM32*EL)/(Sqrt[2]*sw),
     gc71 -> (CKM13*EL)/(Sqrt[2]*sw),
     gc72 -> (CKM11*EL)/(Sqrt[2]*sw),
     gc73 -> (CKM12*EL)/(Sqrt[2]*sw),
     gc74 -> EL/(Sqrt[2]*sw),
     gc75 -> EL/(Sqrt[2]*sw),
     gc76 -> EL/(Sqrt[2]*sw),
     gc77 -> (EL*Conjugate[CKM23])/(Sqrt[2]*sw),
     gc78 -> (EL*Conjugate[CKM33])/(Sqrt[2]*sw),
     gc79 -> (EL*Conjugate[CKM13])/(Sqrt[2]*sw),
     gc80 -> (EL*Conjugate[CKM21])/(Sqrt[2]*sw),
     gc81 -> (EL*Conjugate[CKM31])/(Sqrt[2]*sw),
     gc82 -> (EL*Conjugate[CKM11])/(Sqrt[2]*sw),
     gc83 -> (EL*Conjugate[CKM22])/(Sqrt[2]*sw),
     gc84 -> (EL*Conjugate[CKM32])/(Sqrt[2]*sw),
     gc85 -> (EL*Conjugate[CKM12])/(Sqrt[2]*sw),
     gc86L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc86R -> (EL*sw)/(3*cw),
     gc87L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc87R -> (EL*sw)/(3*cw),
     gc88L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc88R -> (EL*sw)/(3*cw),
     gc89L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc89R -> (EL*sw)/cw,
     gc90L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc90R -> (EL*sw)/cw,
     gc91L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc91R -> (EL*sw)/cw,
     gc92L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc92R -> (-2*EL*sw)/(3*cw),
     gc93L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc93R -> (-2*EL*sw)/(3*cw),
     gc94L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc94R -> (-2*EL*sw)/(3*cw),
     gc95 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc96 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc97 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc98L -> ydo*Conjugate[CKM21],
     gc98R -> -(yc*Conjugate[CKM21]),
     gc99L -> ydo*Conjugate[CKM31],
     gc99R -> -(yt*Conjugate[CKM31]),
     gc100L -> ydo*Conjugate[CKM11],
     gc100R -> -(yup*Conjugate[CKM11]),
     gc101 -> -(ydo/Sqrt[2]),
     gc102L -> -(ydo/Sqrt[2]),
     gc102R -> ydo/Sqrt[2],
     gc103L -> CKM21*yc,
     gc103R -> -(CKM21*ydo),
     gc104L -> CKM31*yt,
     gc104R -> -(CKM31*ydo),
     gc105L -> CKM11*yup,
     gc105R -> -(CKM11*ydo),
     gc106L -> ys*Conjugate[CKM22],
     gc106R -> -(yc*Conjugate[CKM22]),
     gc107L -> ys*Conjugate[CKM32],
     gc107R -> -(yt*Conjugate[CKM32]),
     gc108L -> ys*Conjugate[CKM12],
     gc108R -> -(yup*Conjugate[CKM12]),
     gc109 -> -(ys/Sqrt[2]),
     gc110L -> -(ys/Sqrt[2]),
     gc110R -> ys/Sqrt[2],
     gc111L -> CKM22*yc,
     gc111R -> -(CKM22*ys),
     gc112L -> CKM32*yt,
     gc112R -> -(CKM32*ys),
     gc113L -> CKM12*yup,
     gc113R -> -(CKM12*ys),
     gc114L -> yb*Conjugate[CKM23],
     gc114R -> -(yc*Conjugate[CKM23]),
     gc115L -> yb*Conjugate[CKM33],
     gc115R -> -(yt*Conjugate[CKM33]),
     gc116L -> yb*Conjugate[CKM13],
     gc116R -> -(yup*Conjugate[CKM13]),
     gc117 -> -(yb/Sqrt[2]),
     gc118L -> -(yb/Sqrt[2]),
     gc118R -> yb/Sqrt[2],
     gc119L -> CKM23*yc,
     gc119R -> -(CKM23*yb),
     gc120L -> CKM33*yt,
     gc120R -> -(CKM33*yb),
     gc121L -> CKM13*yup,
     gc121R -> -(CKM13*yb),
     gc122 -> -(ye/Sqrt[2]),
     gc123L -> -(ye/Sqrt[2]),
     gc123R -> ye/Sqrt[2],
     gc124 -> ye,
     gc125L -> 1,
     gc125R -> -ye,
     gc126 -> -(ym/Sqrt[2]),
     gc127L -> -(ym/Sqrt[2]),
     gc127R -> ym/Sqrt[2],
     gc128 -> ym,
     gc129L -> 1,
     gc129R -> -ym,
     gc130 -> -(ytau/Sqrt[2]),
     gc131L -> -(ytau/Sqrt[2]),
     gc131R -> ytau/Sqrt[2],
     gc132 -> ytau,
     gc133L -> 1,
     gc133R -> -ytau,
     gc134 -> -(yup/Sqrt[2]),
     gc135L -> yup/Sqrt[2],
     gc135R -> -(yup/Sqrt[2]),
     gc136 -> -(yc/Sqrt[2]),
     gc137L -> yc/Sqrt[2],
     gc137R -> -(yc/Sqrt[2]),
     gc138 -> -(yt/Sqrt[2]),
     gc139L -> yt/Sqrt[2],
     gc139R -> -(yt/Sqrt[2]),
     gc140 -> EL,
     gc141 -> -EL,
     gc143 -> EL,
     gc146 -> -EL,
     gc147 -> -((cw*EL)/sw),
     gc149 -> (cw*EL)/sw,
     gc151 -> -EL,
     gc154 -> EL,
     gc155 -> (cw*EL)/sw,
     gc157 -> -((cw*EL)/sw),
     gc159 -> (cw*EL)/sw,
     gc161 -> -((cw*EL)/sw),
     gc163 -> GS};

