(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)



(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} },

V[41] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Zp",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mZp,
    Indices -> {} },

U[41] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mZp,
    Indices -> {} },

F[19] == {
    SelfConjugate -> True,
    Indices -> {Index[Generation]},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MNR }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ V[41] ] = GaugeXi[Zp];
GaugeXi[ U[41] ] = GaugeXi[Zp];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MM;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MH[ ___ ] := MH;
mZp[ ___ ] := mZp;
MNR[ 1 ] := MeR
MNR[ 2 ] := MMR
MNR[ 3 ] := MTAR


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ F[19, {1}] ] := "veR"
TheLabel[ F[19, {2}] ] := "vmR"
TheLabel[ F[19, {3}] ] := "vtR"


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2])}, {gc1*SUNF[e1x2, e2x2, e3x2]}, {gc1*SUNF[e1x2, e2x2, e3x2]}, {-(gc1*SUNF[e1x2, e2x2, e3x2])}, {-(gc1*SUNF[e1x2, e2x2, e3x2])}, {gc1*SUNF[e1x2, e2x2, e3x2]}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2])}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2])}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2])}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3}, {I*gc3}, {I*gc3}, {(-I)*gc3}, {(-I)*gc3}, {I*gc3}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4}, {(-I)*gc4}, {(2*I)*gc4}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5}, {I*gc5}, {I*gc5}, {(-I)*gc5}, {(-I)*gc5}, {I*gc5}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6}, {(-I)*gc6}, {(2*I)*gc6}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7}, {I*gc7}, {I*gc7}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8}, {(-I)*gc8}, {(2*I)*gc8}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc19}, {I*gc19}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-EL^2/(2*sw)}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*sw)}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc23}, {I*gc23}},

C[ -S[3] , S[1] , V[3] ] == {{-gc24}, {gc24}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw)}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw)}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc28}, {I*gc28}},

C[ S[3] , S[1] , -V[3] ] == {{-gc29}, {gc29}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw)}},

C[ S[2] , S[1] , V[2] ] == {{-gc35}, {gc35}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc36}, {I*gc36}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw)}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw)}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-EL^2/(2*cw)}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*cw)}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2)}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2)}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2)}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2)}},

C[ -F[1, {e2x2}] , F[2, {e1x2}] , V[3] ] == {{I*gc47*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[1, {e2x2}] , F[1, {e1x2}] , V[2] ] == {{I*gc48*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[2, {e3x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc49*IndexDelta[e2x2, e3x2]}, {I*gc49*IndexDelta[e2x2, e3x2]}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc50*IndexDelta[e1x2, e2x2]}, {0}},

C[ -F[2, {e2x2}] , F[2, {e1x2}] , V[2] ] == {{I*gc51L*IndexDelta[e1x2, e2x2]}, {I*gc51R*IndexDelta[e1x2, e2x2]}},

C[ -F[3, {e3x2, e3x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc52*IndexDelta[e2x2, e3x2]*IndexDelta[e2x3, e3x3]}, {I*gc52*IndexDelta[e2x2, e3x2]*IndexDelta[e2x3, e3x3]}},

C[ -F[3, {e3x2, e3x3}] , F[3, {e2x2, e2x3}] , V[4, {e1x2}] ] == {{I*gc53*IndexDelta[e2x2, e3x2]*SUNT[e1x2, e3x3, e2x3]}, {I*gc53*IndexDelta[e2x2, e3x2]*SUNT[e1x2, e3x3, e2x3]}},

C[ -F[3, {e2x2, e2x3}] , F[4, {e1x2, e1x3}] , V[3] ] == {{I*gc54[e2x2, e1x2]*IndexDelta[e1x3, e2x3]}, {0}},

C[ -F[3, {e2x2, e2x3}] , F[3, {e1x2, e1x3}] , V[2] ] == {{I*gc55L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {I*gc55R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}},

C[ -F[4, {e3x2, e3x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc56*IndexDelta[e2x2, e3x2]*IndexDelta[e2x3, e3x3]}, {I*gc56*IndexDelta[e2x2, e3x2]*IndexDelta[e2x3, e3x3]}},

C[ -F[4, {e2x2, e2x3}] , F[4, {e1x2, e1x3}] , V[4, {e3x2}] ] == {{I*gc57*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e2x3, e1x3]}, {I*gc57*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e2x3, e1x3]}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc58[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {0}},

C[ -F[4, {e2x2, e2x3}] , F[4, {e1x2, e1x3}] , V[2] ] == {{I*gc59L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {I*gc59R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e3x2, e3x3}] , -S[3] ] == {{gc60L[e1x2, e3x2]*IndexDelta[e1x3, e3x3]}, {gc60R[e1x2, e3x2]*IndexDelta[e1x3, e3x3]}},

C[ -F[4, {e2x2, e2x3}] , F[4, {e1x2, e1x3}] , S[2] ] == {{gc61L[e2x2, e1x2]*IndexDelta[e1x3, e2x3]}, {gc61R[e2x2, e1x2]*IndexDelta[e1x3, e2x3]}},

C[ -F[4, {e2x2, e2x3}] , F[4, {e1x2, e1x3}] , S[1] ] == {{I*gc62L[e2x2, e1x2]*IndexDelta[e1x3, e2x3]}, {I*gc62R[e2x2, e1x2]*IndexDelta[e1x3, e2x3]}},

C[ -F[2, {e2x2}] , F[1, {e3x2}] , -S[3] ] == {{gc63[e2x2, e3x2]}, {0}},

C[ -F[2, {e3x2}] , F[2, {e2x2}] , S[2] ] == {{gc64L[e3x2, e2x2]}, {gc64R[e3x2, e2x2]}},

C[ -F[2, {e3x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc65L[e3x2, e2x2]}, {I*gc65R[e3x2, e2x2]}},

C[ -F[3, {e3x2, e3x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{gc66L[e3x2, e2x2]*IndexDelta[e2x3, e3x3]}, {gc66R[e3x2, e2x2]*IndexDelta[e2x3, e3x3]}},

C[ -F[3, {e3x2, e3x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc67L[e3x2, e2x2]*IndexDelta[e2x3, e3x3]}, {I*gc67R[e3x2, e2x2]*IndexDelta[e2x3, e3x3]}},

C[ -F[3, {e3x2, e3x3}] , F[4, {e1x2, e1x3}] , S[3] ] == {{gc68L[e3x2, e1x2]*IndexDelta[e1x3, e3x3]}, {gc68R[e3x2, e1x2]*IndexDelta[e1x3, e3x3]}},

C[ -F[1, {e3x2}] , F[2, {e2x2}] , S[3] ] == {{0}, {gc69R[e3x2, e2x2]}},

C[ -U[1] , U[32] , V[3] ] == {{I*gc70}, {I*gc70}, {0}},

C[ -U[1] , U[31] , -V[3] ] == {{I*gc71}, {I*gc71}, {0}},

C[ -S[3] , -U[32] , U[1] ] == {{(EL^2*vev)/(2*sw)}},

C[ -U[32] , U[1] , -V[3] ] == {{I*gc73}, {I*gc73}, {0}},

C[ S[2] , -U[32] , U[32] ] == {{-(EL^2*vev)/(4*sw^2)}},

C[ S[1] , -U[32] , U[32] ] == {{((-I/4)*EL^2*vev)/sw^2}},

C[ -U[32] , U[32] , V[1] ] == {{I*gc76}, {I*gc76}, {0}},

C[ -U[32] , U[32] , V[2] ] == {{I*gc77}, {I*gc77}, {0}},

C[ -S[3] , -U[32] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2)}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gc79}, {I*gc79}, {0}},

C[ S[3] , -U[31] , U[1] ] == {{-(EL^2*vev)/(2*sw)}},

C[ -U[31] , U[1] , V[3] ] == {{I*gc81}, {I*gc81}, {0}},

C[ S[2] , -U[31] , U[31] ] == {{(EL^2*vev)/(4*sw^2)}},

C[ S[1] , -U[31] , U[31] ] == {{((-I/4)*EL^2*vev)/sw^2}},

C[ -U[31] , U[31] , V[1] ] == {{I*gc84}, {I*gc84}, {0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gc85}, {I*gc85}, {0}},

C[ S[3] , -U[31] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2)}},

C[ -U[31] , U[2] , V[3] ] == {{I*gc87}, {I*gc87}, {0}},

C[ S[3] , -U[2] , U[32] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2)}},

C[ -U[2] , U[32] , V[3] ] == {{I*gc89}, {I*gc89}, {0}},

C[ -S[3] , -U[2] , U[31] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2)}},

C[ -U[2] , U[31] , -V[3] ] == {{I*gc91}, {I*gc91}, {0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2)}},

C[ -U[4, {e2x1}] , U[4, {e3x1}] , V[4, {e1x2}] ] == {{gc93*SUNF[e1x2, e2x1, e3x1]}, {gc93*SUNF[e1x2, e2x1, e3x1]}, {0}},

C[ -F[4, {e2x2, e2x3}] , F[4, {e1x2, e1x3}] , V[41] ] == {{I*gc94L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {I*gc94R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}},

C[ -F[2, {e2x2}] , F[2, {e1x2}] , V[41] ] == {{I*gc95L*IndexDelta[e1x2, e2x2]}, {I*gc95R*IndexDelta[e1x2, e2x2]}},

C[ -F[3, {e2x2, e2x3}] , F[3, {e1x2, e1x3}] , V[41] ] == {{I*gc96L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {I*gc96R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}},

C[ -F[1, {e2x2}] , F[1, {e1x2}] , V[41] ] == {{I*gc97*IndexDelta[e1x2, e2x2]}, {0}},

C[ F[19, {e1x2}] , F[19, {e2x2}] , V[41] ] == {{I*gc98L*IndexDelta[e1x2, e2x2]}, {I*gc98R*IndexDelta[e1x2, e2x2]}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> EL,
     gc4 -> -EL^2,
     gc5 -> (cw*EL)/sw,
     gc6 -> EL^2/sw^2,
     gc7 -> (cw*EL^2)/sw,
     gc8 -> -((cw^2*EL^2)/sw^2),
     gc19 -> -EL,
     gc23 -> EL/(2*sw),
     gc24 -> -EL/(2*sw),
     gc28 -> -EL/(2*sw),
     gc29 -> -EL/(2*sw),
     gc35 -> -(EL*(cw^2 + sw^2))/(2*cw*sw),
     gc36 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc47 -> EL/(Sqrt[2]*sw),
     gc48 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc49 -> -EL,
     gc50 -> EL/(Sqrt[2]*sw),
     gc51L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc51R -> (EL*sw)/cw,
     gc52 -> (2*EL)/3,
     gc53 -> GS,
     gc54[e2x2_, e1x2_] -> (EL*CKM[e2x2, e1x2])/(Sqrt[2]*sw),
     gc55L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc55R -> (-2*EL*sw)/(3*cw),
     gc56 -> -EL/3,
     gc57 -> GS,
     gc58[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc59L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc59R -> (EL*sw)/(3*cw),
     gc60L[e1x2_, e3x2_] -> IndexSum[Conjugate[CKM[e3x2, Generation$11]]*Conjugate[yd[Generation$11, e1x2]], {Generation$11, 1, 3}],
     gc60R[e1x2_, e3x2_] -> -IndexSum[Conjugate[CKM[Generation$11, e1x2]]*yu[Generation$11, e3x2], {Generation$11, 1, 3}],
     gc61L[e2x2_, e1x2_] -> -(Conjugate[yd[e1x2, e2x2]]/Sqrt[2]),
     gc61R[e2x2_, e1x2_] -> yd[e2x2, e1x2]/Sqrt[2],
     gc62L[e2x2_, e1x2_] -> -(Conjugate[yd[e1x2, e2x2]]/Sqrt[2]),
     gc62R[e2x2_, e1x2_] -> -(yd[e2x2, e1x2]/Sqrt[2]),
     gc63[e2x2_, e3x2_] -> Conjugate[yl[e3x2, e2x2]],
     gc64L[e3x2_, e2x2_] -> -(Conjugate[yl[e2x2, e3x2]]/Sqrt[2]),
     gc64R[e3x2_, e2x2_] -> yl[e3x2, e2x2]/Sqrt[2],
     gc65L[e3x2_, e2x2_] -> -(Conjugate[yl[e2x2, e3x2]]/Sqrt[2]),
     gc65R[e3x2_, e2x2_] -> -(yl[e3x2, e2x2]/Sqrt[2]),
     gc66L[e3x2_, e2x2_] -> Conjugate[yu[e2x2, e3x2]]/Sqrt[2],
     gc66R[e3x2_, e2x2_] -> -(yu[e3x2, e2x2]/Sqrt[2]),
     gc67L[e3x2_, e2x2_] -> -(Conjugate[yu[e2x2, e3x2]]/Sqrt[2]),
     gc67R[e3x2_, e2x2_] -> -(yu[e3x2, e2x2]/Sqrt[2]),
     gc68L[e3x2_, e1x2_] -> IndexSum[CKM[Generation$11, e1x2]*Conjugate[yu[Generation$11, e3x2]], {Generation$11, 1, 3}],
     gc68R[e3x2_, e1x2_] -> -IndexSum[CKM[e3x2, Generation$11]*yd[Generation$11, e1x2], {Generation$11, 1, 3}],
     gc69L -> 1,
     gc69R[e3x2_, e2x2_] -> -yl[e3x2, e2x2],
     gc70 -> EL,
     gc71 -> -EL,
     gc73 -> EL,
     gc76 -> -EL,
     gc77 -> -((cw*EL)/sw),
     gc79 -> (cw*EL)/sw,
     gc81 -> -EL,
     gc84 -> EL,
     gc85 -> (cw*EL)/sw,
     gc87 -> -((cw*EL)/sw),
     gc89 -> (cw*EL)/sw,
     gc91 -> -((cw*EL)/sw),
     gc93 -> GS,
     gc94L -> gX*qXdL,
     gc94R -> gX*qXdR,
     gc95L -> gX*qXeL,
     gc95R -> gX*qXeR,
     gc96L -> gX*qXuL,
     gc96R -> gX*qXuR,
     gc97 -> gX*qXvL,
     gc98L -> -(gX*qXvR),
     gc98R -> gX*qXvR};

