(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)



(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MM,
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "tt" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "phi" },

S[3] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "phi2" },

S[4] == {
    SelfConjugate -> True,
    QuantumNumbers -> {},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MSS,
    Indices -> {},
    PropagatorLabel -> "SS" },

V[5] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MX,
    Indices -> {},
    PropagatorLabel -> "Zp" }
}


(*        Definitions       *)

GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ S[4] ] = GaugeXi[Zp];

Me[ ___ ] := Me;
MM[ ___ ] := MM;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MH[ ___ ] := MH;
MSS[ ___ ] := MSS;
MX[ ___ ] := MX;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3, 0, 0}, {I*gc3, 0, 0}, {I*gc3, 0, 0}, {(-I)*gc3, 0, 0}, {(-I)*gc3, 0, 0}, {I*gc3, 0, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4, 0, 0}, {(-I)*gc4, 0, 0}, {(2*I)*gc4, 0, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5, 0, 0}, {I*gc5, 0, 0}, {I*gc5, 0, 0}, {(-I)*gc5, 0, 0}, {(-I)*gc5, 0, 0}, {I*gc5, 0, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6, 0, 0}, {(-I)*gc6, 0, 0}, {(2*I)*gc6, 0, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7, 0, 0}, {I*gc7, 0, 0}, {I*gc7, 0, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8, 0, 0}, {(-I)*gc8, 0, 0}, {(2*I)*gc8, 0, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*v, 0, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*v)/sw^2, 0, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0, 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*v)/(cw^2*sw^2), 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[4, {e3x2}] ] == {{I*gc15*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc15*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[4, {e3x2}] ] == {{I*gc16*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc16*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[4, {e1x2}] ] == {{I*gc17*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc17*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[4, {e3x2}] ] == {{I*gc18*SUNT[e3x2, e2x2, e1x2], 0, 0}, {I*gc18*SUNT[e3x2, e2x2, e1x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[4, {e1x2}] ] == {{I*gc19*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc19*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[4, {e1x2}] ] == {{I*gc20*SUNT[e1x2, e3x2, e2x2], 0, 0}, {I*gc20*SUNT[e1x2, e3x2, e2x2], 0, 0}},

C[ -F[12, {e3x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc21*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc21*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[10, {e3x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc22*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc22*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc23*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc23*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc24, 0, 0}, {I*gc24, 0, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc25, 0, 0}, {I*gc25, 0, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc26, 0, 0}, {I*gc26, 0, 0}},

C[ -F[8, {e3x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc27*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc27*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc28*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc28*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc29*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc29*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc30, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc31, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc32, 0, 0}, {0, 0, 0}},

C[ -F[8, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc33*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc34*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc35*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc36*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc37*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[9, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc38*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[12, {e1x2}] , V[3] ] == {{I*gc39*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[10, {e1x2}] , V[3] ] == {{I*gc40*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[7, {e2x2}] , F[11, {e1x2}] , V[3] ] == {{I*gc41*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc42, 0, 0}, {0, 0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc43, 0, 0}, {0, 0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc44, 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc45*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc46*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc47*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc48*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc49*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc50*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e2x2}] , F[8, {e1x2}] , -V[3] ] == {{I*gc51*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc52*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc53*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[2] ] == {{I*gc54L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc54R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[2] ] == {{I*gc55L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc55R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[11, {e2x2}] , F[11, {e1x2}] , V[2] ] == {{I*gc56L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc56R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc57L, 0, 0}, {I*gc57R, 0, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc58L, 0, 0}, {I*gc58R, 0, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc59L, 0, 0}, {I*gc59R, 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[2] ] == {{I*gc60L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc60R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e2x2}] , F[9, {e1x2}] , V[2] ] == {{I*gc61L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc61R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[7, {e2x2}] , F[7, {e1x2}] , V[2] ] == {{I*gc62L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc62R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc63, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc64, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc65, 0, 0}, {0, 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , S[1] ] == {{I*gc66*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc66*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[11, {e3x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc67*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc67*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , S[1] ] == {{I*gc68*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc68*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc69, 0, 0}, {I*gc69, 0, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc70, 0, 0}, {I*gc70, 0, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc71, 0, 0}, {I*gc71, 0, 0}},

C[ -F[7, {e3x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc72*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc72*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , S[1] ] == {{I*gc73*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc73*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e3x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc74*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc74*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -U[5, {e2x1}] , U[5, {e3x1}] , V[4, {e1x2}] ] == {{gc75*SUNF[e1x2, e2x1, e3x1], 0, 0}, {gc75*SUNF[e1x2, e2x1, e3x1], 0, 0}, {0, 0, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*lamX, 0, 0}},

C[ S[4] , S[4] , S[4] ] == {{(-6*I)*lamX*vX, 0, 0}},

C[ S[4] , S[4] , V[5] , V[5] ] == {{(2*I)*gX^2*qxS^2, 0, 0}},

C[ S[4] , V[5] , V[5] ] == {{(2*I)*gX^2*qxS^2*vX, 0, 0}},

C[ -F[12, {e2x2}] , F[12, {e1x2}] , V[5] ] == {{I*gc80L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc80R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[10, {e2x2}] , F[10, {e1x2}] , V[5] ] == {{I*gc81L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc81R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[11, {e2x2}] , F[11, {e1x2}] , V[5] ] == {{I*gc82L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc82R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[4] , F[4] , V[5] ] == {{I*gc83L, 0, 0}, {I*gc83R, 0, 0}},

C[ -F[5] , F[5] , V[5] ] == {{I*gc84L, 0, 0}, {I*gc84R, 0, 0}},

C[ -F[6] , F[6] , V[5] ] == {{I*gc85L, 0, 0}, {I*gc85R, 0, 0}},

C[ -F[8, {e2x2}] , F[8, {e1x2}] , V[5] ] == {{I*gc86L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc86R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[9, {e2x2}] , F[9, {e1x2}] , V[5] ] == {{I*gc87L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc87R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[7, {e2x2}] , F[7, {e1x2}] , V[5] ] == {{I*gc88L*IndexDelta[e1x2, e2x2], 0, 0}, {I*gc88R*IndexDelta[e1x2, e2x2], 0, 0}},

C[ -F[1] , F[1] , V[5] ] == {{I*gc89, 0, 0}, {0, 0, 0}},

C[ -F[2] , F[2] , V[5] ] == {{I*gc90, 0, 0}, {0, 0, 0}},

C[ -F[3] , F[3] , V[5] ] == {{I*gc91, 0, 0}, {0, 0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> gw*sw,
     gc4 -> -(gw^2*sw^2),
     gc5 -> cw*gw,
     gc6 -> gw^2,
     gc7 -> cw*gw^2*sw,
     gc8 -> -(cw^2*gw^2),
     gc15 -> GS,
     gc16 -> GS,
     gc17 -> GS,
     gc18 -> GS,
     gc19 -> GS,
     gc20 -> GS,
     gc21 -> -EL/3,
     gc22 -> -EL/3,
     gc23 -> -EL/3,
     gc24 -> -EL,
     gc25 -> -EL,
     gc26 -> -EL,
     gc27 -> (2*EL)/3,
     gc28 -> (2*EL)/3,
     gc29 -> (2*EL)/3,
     gc30 -> EL/(Sqrt[2]*sw),
     gc31 -> EL/(Sqrt[2]*sw),
     gc32 -> EL/(Sqrt[2]*sw),
     gc33 -> (CKM23*EL)/(Sqrt[2]*sw),
     gc34 -> (CKM21*EL)/(Sqrt[2]*sw),
     gc35 -> (CKM22*EL)/(Sqrt[2]*sw),
     gc36 -> (CKM33*EL)/(Sqrt[2]*sw),
     gc37 -> (CKM31*EL)/(Sqrt[2]*sw),
     gc38 -> (CKM32*EL)/(Sqrt[2]*sw),
     gc39 -> (CKM13*EL)/(Sqrt[2]*sw),
     gc40 -> (CKM11*EL)/(Sqrt[2]*sw),
     gc41 -> (CKM12*EL)/(Sqrt[2]*sw),
     gc42 -> EL/(Sqrt[2]*sw),
     gc43 -> EL/(Sqrt[2]*sw),
     gc44 -> EL/(Sqrt[2]*sw),
     gc45 -> (EL*Conjugate[CKM23])/(Sqrt[2]*sw),
     gc46 -> (EL*Conjugate[CKM33])/(Sqrt[2]*sw),
     gc47 -> (EL*Conjugate[CKM13])/(Sqrt[2]*sw),
     gc48 -> (EL*Conjugate[CKM21])/(Sqrt[2]*sw),
     gc49 -> (EL*Conjugate[CKM31])/(Sqrt[2]*sw),
     gc50 -> (EL*Conjugate[CKM11])/(Sqrt[2]*sw),
     gc51 -> (EL*Conjugate[CKM22])/(Sqrt[2]*sw),
     gc52 -> (EL*Conjugate[CKM32])/(Sqrt[2]*sw),
     gc53 -> (EL*Conjugate[CKM12])/(Sqrt[2]*sw),
     gc54L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc54R -> (EL*sw)/(3*cw),
     gc55L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc55R -> (EL*sw)/(3*cw),
     gc56L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc56R -> (EL*sw)/(3*cw),
     gc57L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc57R -> (EL*sw)/cw,
     gc58L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc58R -> (EL*sw)/cw,
     gc59L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc59R -> (EL*sw)/cw,
     gc60L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc60R -> (-2*EL*sw)/(3*cw),
     gc61L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc61R -> (-2*EL*sw)/(3*cw),
     gc62L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc62R -> (-2*EL*sw)/(3*cw),
     gc63 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc64 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc65 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc66 -> -(ydo/Sqrt[2]),
     gc67 -> -(ys/Sqrt[2]),
     gc68 -> -(yb/Sqrt[2]),
     gc69 -> -(ye/Sqrt[2]),
     gc70 -> -(ym/Sqrt[2]),
     gc71 -> -(ytau/Sqrt[2]),
     gc72 -> -(yup/Sqrt[2]),
     gc73 -> -(yc/Sqrt[2]),
     gc74 -> -(yt/Sqrt[2]),
     gc75 -> GS,
     gc80L -> gX*qxQ,
     gc80R -> gX*qxD,
     gc81L -> gX*qxQ,
     gc81R -> gX*qxD,
     gc82L -> gX*qxQ,
     gc82R -> gX*qxD,
     gc83L -> gX*qxL,
     gc83R -> gX*qxE,
     gc84L -> gX*qxL,
     gc84R -> gX*qxE,
     gc85L -> gX*qxL,
     gc85R -> gX*qxE,
     gc86L -> gX*qxQ,
     gc86R -> gX*qxU,
     gc87L -> gX*qxQ,
     gc87R -> gX*qxU,
     gc88L -> gX*qxQ,
     gc88R -> gX*qxU,
     gc89 -> gX*qxL,
     gc90 -> gX*qxL,
     gc91 -> gX*qxL};

