(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)



(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[SU2F] ] = Range[ 2 ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[SU2F]},
    QuantumNumbers -> {-Y/2, LeptonNumber},
    PropagatorLabel -> "L",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {-Y, LeptonNumber},
    PropagatorLabel -> "E",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[3] == {
    SelfConjugate -> True,
    Indices -> {Index[Generation]},
    PropagatorLabel -> "N",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MassNr },

S[1] == {
    SelfConjugate -> False,
    Indices -> {Index[SU2F]},
    QuantumNumbers -> {Y/2, 0},
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[2] == {
    SelfConjugate -> False,
    Indices -> {Index[SU2F]},
    QuantumNumbers -> {Y/2, -LeptonNumber},
    PropagatorLabel -> "eta",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> Meta },

V[1] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "B",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 },

V[2] == {
    SelfConjugate -> True,
    Indices -> {Index[SU2W]},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 },

V[3] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> G,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[B];
GaugeXi[ V[2] ] = GaugeXi[W];
GaugeXi[ V[3] ] = GaugeXi[G];

MassNr[ ___ ] := MassNr;
Meta[ ___ ] := Meta;


TheLabel[ F[1, {1, _}] ] := "L1";
TheLabel[ F[1, {1}] ] := "L1";
TheLabel[ F[1, {2, _}] ] := "L2";
TheLabel[ F[1, {2}] ] := "L2";
TheLabel[ F[1, {3, _}] ] := "L3";
TheLabel[ F[1, {3}] ] := "L3";
TheLabel[ F[2, {1}] ] := "E1";
TheLabel[ F[2, {2}] ] := "E2";
TheLabel[ F[2, {3}] ] := "E3";
TheLabel[ F[3, {1}] ] := "N1";
TheLabel[ F[3, {2}] ] := "N2";
TheLabel[ F[3, {3}] ] := "N3";
TheLabel[ S[1, {__}] ] := TheLabel[S[1]];
TheLabel[ S[2, {__}] ] := TheLabel[S[2]];
TheLabel[ V[2, {__}] ] := TheLabel[V[2]];
TheLabel[ V[3, {__}] ] := TheLabel[V[3]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[3, {e1x2}] , V[3, {e2x2}] , V[3, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0, 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0, 0}},

C[ V[3, {e1x2}] , V[3, {e2x2}] , V[3, {e3x2}] , V[3, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0, 0}},

C[ -S[2, {e1x1}] , -S[2, {e2x1}] , S[1, {e3x1}] , S[1, {e4x1}] ] == {{(-I/2)*Lam3*(IndexDelta[e1x1, e4x1]*IndexDelta[e2x1, e3x1] + IndexDelta[e1x1, e3x1]*IndexDelta[e2x1, e4x1]), 0, 0}},

C[ S[2, {e1x1}] , -S[2, {e2x1}] , S[1, {e3x1}] , -S[1, {e4x1}] ] == {{(-I)*(Lam2*IndexDelta[e1x1, e4x1]*IndexDelta[e2x1, e3x1] + Lam1*IndexDelta[e1x1, e2x1]*IndexDelta[e3x1, e4x1]), 0, 0}},

C[ S[2, {e1x1}] , S[2, {e2x1}] , -S[1, {e3x1}] , -S[1, {e4x1}] ] == {{(-I/2)*Lam3*(IndexDelta[e1x1, e4x1]*IndexDelta[e2x1, e3x1] + IndexDelta[e1x1, e3x1]*IndexDelta[e2x1, e4x1]), 0, 0}},

C[ V[2, {e1x2}] , V[2, {e2x2}] , V[2, {e3x2}] ] == {{-gc6[e1x2, e2x2, e3x2], 0, 0}, {gc6[e1x2, e2x2, e3x2], 0, 0}, {gc6[e1x2, e2x2, e3x2], 0, 0}, {-gc6[e1x2, e2x2, e3x2], 0, 0}, {-gc6[e1x2, e2x2, e3x2], 0, 0}, {gc6[e1x2, e2x2, e3x2], 0, 0}},

C[ V[2, {e1x2}] , V[2, {e2x2}] , V[2, {e3x2}] , V[2, {e4x2}] ] == {{I*gc7*IndexDelta[e1x2, e4x2]*IndexDelta[e2x2, e3x2], 0, 0}, {I*gc7*IndexDelta[e1x2, e3x2]*IndexDelta[e2x2, e4x2], 0, 0}, {I*gc7*IndexDelta[e1x2, e2x2]*IndexDelta[e3x2, e4x2], 0, 0}},

C[ -F[2, {e1x2}] , F[1, {e3x2, e3x3}] , -S[1, {e2x1}] ] == {{I*gc8[e1x2]*IndexDelta[e1x2, e3x2]*IndexDelta[e2x1, e3x3], 0, 0}, {0, 0, 0}},

C[ -F[1, {e3x2, e3x3}] , F[2, {e1x2}] , S[1, {e2x1}] ] == {{0, 0, 0}, {I*gc9R[e1x2]*IndexDelta[e1x2, e3x2]*IndexDelta[e2x1, e3x3], 0, 0}},

C[ F[3, {e3x2}] , F[1, {e2x2, e2x3}] , S[2, {e1x1}] ] == {{I*gc10[e2x2, e2x3, e1x1]*IndexDelta[e2x2, e3x2], 0, 0}, {0, 0, 0}},

C[ -F[1, {e2x2, e2x3}] , F[3, {e3x2}] , -S[2, {e1x1}] ] == {{0, 0, 0}, {I*gc11R[e2x2, e2x3, e1x1]*IndexDelta[e2x2, e3x2], 0, 0}},

C[ -F[1, {e3x2, e3x3}] , F[1, {e2x2, e2x3}] , V[1] ] == {{I*gc12*IndexDelta[e2x2, e3x2]*IndexDelta[e2x3, e3x3], 0, 0}, {0, 0, 0}},

C[ -F[1, {e2x2, e2x3}] , F[1, {e1x2, e1x3}] , V[2, {e3x2}] ] == {{I*gc13[e2x3, e1x3, e3x2]*IndexDelta[e1x2, e2x2], 0, 0}, {0, 0, 0}},

C[ -F[2, {e3x2}] , F[2, {e2x2}] , V[1] ] == {{0, 0, 0}, {I*gc14R*IndexDelta[e2x2, e3x2], 0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -gS,
     gc2 -> -gS^2,
     gc6[e1x2_, e2x2_, e3x2_] -> -(gW*Eps[e1x2, e2x2, e3x2]),
     gc7 -> -12*gW^2,
     gc8[e1x2_] -> -yl[e1x2],
     gc9L -> 1,
     gc9R[e1x2_] -> -yl[e1x2],
     gc10[e2x2_, e2x3_, e1x1_] -> Eps[e1x1, e2x3]*yn[e2x2],
     gc11L -> 1,
     gc11R[e2x2_, e2x3_, e1x1_] -> Eps[e1x1, e2x3]*yn[e2x2],
     gc12 -> -gY/2,
     gc13[e2x3_, e1x3_, e3x2_] -> gW*T2[e3x2, e2x3, e1x3],
     gc14L -> 1,
     gc14R -> -gY};

