(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)



(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Zp",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mZp,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mZp,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[1] == {
    SelfConjugate -> False,
    PropagatorLabel -> "\[Phi]",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mphi,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    PropagatorLabel -> "\[Psi]",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mpsi,
    Indices -> {} },

F[2] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[Zp];
GaugeXi[ V[2] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[Zp];
GaugeXi[ U[2] ] = GaugeXi[G];

mZp[ ___ ] := mZp;
mphi[ ___ ] := mphi;
mpsi[ ___ ] := mpsi;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD
Md[ 1 ] := MD
Md[ 2, _ ] := MS
Md[ 2 ] := MS
Md[ 3, _ ] := MB
Md[ 3 ] := MB


TheLabel[ V[2, {__}] ] := TheLabel[V[2]];
TheLabel[ U[2, {__}] ] := TheLabel[U[2]];
TheLabel[ F[2, {1, _}] ] := "u";
TheLabel[ F[2, {1}] ] := "u";
TheLabel[ F[2, {2, _}] ] := "c";
TheLabel[ F[2, {2}] ] := "c";
TheLabel[ F[2, {3, _}] ] := "t";
TheLabel[ F[2, {3}] ] := "t";
TheLabel[ F[3, {1, _}] ] := "d"
TheLabel[ F[3, {1}] ] := "d"
TheLabel[ F[3, {2, _}] ] := "s"
TheLabel[ F[3, {2}] ] := "s"
TheLabel[ F[3, {3, _}] ] := "b"
TheLabel[ F[3, {3}] ] := "b"


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , -S[1] , V[1] ] == {{(-I)*gc1}, {I*gc1}},

C[ S[1] , -S[1] , V[1] , V[1] ] == {{(2*I)*gX^2*qXphi^2}},

C[ -F[1] , F[1] , V[1] ] == {{I*gc3L}, {I*gc3R}},

C[ -F[2, {e3x2, e3x3}] , F[2, {e2x2, e2x3}] , V[2, {e1x2}] ] == {{I*gc4*IndexDelta[e2x2, e3x2]*SUNT[e1x2, e3x3, e2x3]}, {I*gc4*IndexDelta[e2x2, e3x2]*SUNT[e1x2, e3x3, e2x3]}},

C[ -F[2, {e2x2, e2x3}] , F[2, {e1x2, e1x3}] , V[1] ] == {{I*gc5L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {I*gc5R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}},

C[ -F[3, {e2x2, e2x3}] , F[3, {e1x2, e1x3}] , V[2, {e3x2}] ] == {{I*gc6*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e2x3, e1x3]}, {I*gc6*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e2x3, e1x3]}},

C[ -F[3, {e2x2, e2x3}] , F[3, {e1x2, e1x3}] , V[1] ] == {{I*gc7L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}, {I*gc7R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3]}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -(gX*qXphi),
     gc3L -> gX*qXpsiL,
     gc3R -> gX*qXpsiR,
     gc4 -> GS,
     gc5L -> gX*qXuL,
     gc5R -> gX*qXuR,
     gc6 -> GS,
     gc7L -> gX*qXdL,
     gc7R -> gX*qXdR};

